version: "3"

services:
  project:
    image: 'nginx:alpine'
    container_name: nginx
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8088:80'
    networks:
      - minor
    depends_on:
      - minor-fpm

  minor-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: minor-fpm
    volumes:
      - './src:/var/www/html'
    networks:
      - minor

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'employee'
      MYSQL_PASSWORD: 'employee'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'employee'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - minor

volumes:
  my-db:

networks:
  minor:
    external: true
